### PR TITLE
Switched names to match with AV1738.

### PR DESCRIPTION
**Pull request by bkoelman**
AV1738 says: "It is good practice to prefix the method that handles an event with On. For example, a method that handles the Closing event can be named OnClosing."

Since the example in AV1706 refers to the Click event, its handler name should be something with "OnClick" in it.

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Actually, it does follow that guideline, but it also adds the corresponding object involved. This is also how Visual Studio generates them, e.g. `OnButton1Click`, `OnAcceptButtonClick`.

**Comment by bkoelman** [comment]
I did some testing and found that Visual Studio generates events like `button1_Click`. Resharper overrides this, which is configurable. Resharper defaults to the pattern `$object$_$event$`, but the [DotSettings file](https://github.com/dennisdoomen/CSharpGuidelines/blob/master/ReSharper%209%20Code%20Style.DotSettings#L398) in the root of this repo overrides Resharpers' default with: `$object$_On$event$`.

So I assumed that's the pattern you recommend. If you switched to a different pattern, that's fine too of course. I would just like to know your suggested naming convention to implement https://github.com/bkoelman/CSharpGuidelinesAnalyzer/issues/7.

**Comment by dennisdoomen** [comment]
Hmm, so my guideline works against Visual Studio and R#?

**Comment by bkoelman** [comment]
I'm a bit lost on what's going on, actually. Whatever R# settings I specify in v2016.2.2 (Code Editing, C#, Naming Style, Advanced, Event subscriptions on fields/this), it always suggests the following while typing:

```csharp
this.Click += OnClick;
_okButton.Click += OkButtonOnClick;
```

So it takes the target object (changing the format from _camelCase to PascalCase) + "On" + Event name. If the target object is `this`, the first part is omitted.

In my last post I pointed to the wrong issue. It should be: https://github.com/bkoelman/CSharpGuidelinesAnalyzer/issues/32. I believe the analyzer rule definition should be fine with the above.

I've rebased this PR after merge conflicts. Feel free to let me know what's blocking you from accepting this PR. If time permits, I'll see how the latest EAP handles this at a later time...

**Comment by dennisdoomen** [comment]
Hmm, I still disagree with the chance, but the fact that the tooling doesn't agree with me makes me doubt.

**Comment by bkoelman** [comment]
Perhaps you misunderstood my point: Your example in AV1706 is contradicting with the text of your rule AV1738. I would be fine with any convention, but I just need clarity. So what exactly do you not agree about?

**Comment by dennisdoomen** [comment]
Ah, then I prefer `OnButtonClick`

**Comment by bkoelman** [comment]
Thanks, I'll use that for now. We may want to revisit this topic at a later time once more people have had a chance to see how this works out in practice.

**Comment by bkoelman** [comment]
Created https://youtrack.jetbrains.com/issue/RSRP-461586.

**Pull request closed without merging**
