### PR TITLE
Updated AV1570

### LINKED ISSUE #106: AV1570: Update for is-patterns
### Existing rule:
**`Always check the result of an as operation (AV1570)`**
`If you use 'as' to obtain a certain interface reference from an object, always ensure that this operation does not return null. Failure to do so may cause a NullReferenceException at a much later stage if the object did not implement that interface.`

### New language features to consider:
* is-patterns
Testing for interface implementation using `as` nowadays triggers a Resharper refactoring suggestion to replace the expression with an is-pattern. Example:
```csharp
interface IUser { }

class RemoteUser : IUser { }

class Example
{
    void Test(IUser user)
    {
        var remoteUser = user as RemoteUser;
        //                    ~~~~~~~~~~~~~~ Resharper: Use pattern matching

        if (remoteUser != null)
        {
            // ...
        }
    }
}
```
which is then changed to:
```csharp
if (user is RemoteUser remoteUser)
```

I think we should remove this rule, because it advocates outdated language usage.

Aside from that, the description is incorrect: "If you use 'as' to obtain a certain interface reference from an object..." should be reversed. An object either implements the interface, which makes the test redundant -or- the compiler issues an error because no conversion exists. The text should be: "If you use 'as' to safely upcast an interface reference to a certain object..."

### PR DESCRIPTION
**Pull request by bkoelman**
because it advocates outdated language usage.

Fixes #106.

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Should we not replace this old rule with something new?

**Comment by bkoelman** [comment]
> > I think we should remove this rule, because it advocates outdated language usage.

> Agreed.

So I created a PR to remove. But sure, we can keep some form of this. What do you have in mind?

**Comment by dennisdoomen** [comment]
Maybe we should keep the rule in a more shortened version and use the pattern matching syntax as an example how to improve the readability.

**Comment by bkoelman** [comment]
@dennisdoomen I have updated this PR. Can you please review again?

**Pull request merged**
