### PR TITLE
AV2201 static member access

### LINKED ISSUE #218: AV2201: Int32.Parse() vs int.Parse()
The current rule is worded:

> Use C# type aliases instead of the types from the `System` namespace (AV2201) 

> For instance, use `object` instead of `Object`, `string` instead of `String`, and `int` instead of `Int32`. These aliases have been introduced to make the primitive types first class citizens of the C# language, so use them accordingly.

> **Exception:** When referring to static members of those types, it is custom to use the full CLS name, e.g. `Int32.Parse()` instead of `int.Parse()`. The same applies to members that need to specify the type they return, e.g. `ReadInt32`, `GetUInt16`.

So the rule currently prefers `Int32.Parse()` over `int.Parse()`, which is the opposite of the [.editorconfig default](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0049#dotnet_style_predefined_type_for_member_access) and [this StyleCop rule](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1121.md). The C# ECMA spec used to advocate for `int.Parse()` over `Int32.Parse()`, but that guidance was removed in later versions.

The last line of the exception must be kept for CLS compliance, but as far as I know the static member access is just a matter of taste without any technical consequences.

There is nothing wrong with having this preference in itself, but I thought I'd bring it up for reconsideration.

### PR DESCRIPTION
**Pull request by bkoelman**
Fixes #218.

### CODE REVIEW

**Comment by bkoelman** [comment]
Side note: I see that 'develop' is the default branch, while all recent changes have been done in master (it is 41 commits ahead). I remember from the past you liked to use GitFlow, but to me it only adds confusion. When I go the repo, it shows me an outdated version. Given there's limited changes in this repo, wouldn't it be easier to just have a single master branch without develop?

**Comment by dennisdoomen** [comment]
> Side note: I see that 'develop' is the default branch, while all recent changes have been done in master (it is 41 commits ahead). I remember from the past you liked to use GitFlow, but to me it only adds confusion. When I go to the repo, it shows me an outdated version. Given there's limited changes in this repo, wouldn't it be easier to just have a single master branch without develop?

Yeah, you might be right. I was trying to make breaking changes explicit by using semantic versioning.

**Comment by dennisdoomen** [comment]
But this PR is kind of a breaking change since it is the opposite of what we said before. How should we deal with that?

**Comment by bart-degreed** [comment]
Except for spelling corrections, changes to the website generation process and rendered layout, all textual changes are breaking. Adding a new rule breaks all codebases that didn't utilize that rule before. The same for adding an exception to an existing rule. I find the concept of semantic versioning and whether changes are considered breaking of limited use in this repo, because it does not affect binary dependencies. Likewise it makes no sense to deprecate a rule to remove it in the next major version, because removing rules is non-breaking in itself. I'm reasoning from the point of view of a team that needs to adhere to them.

It seems more similar to versioning design documents such as W3C, IEEE etc, where it is common practice to increment the minor version periodically as details are being refined, while major version increments are used for complete redesigns.

**Pull request merged**
